[package]
name = "cfile-rs"
version = "0.3.3"
authors = ["Joshua Karns <jkarns@oswego.edu>"]
description = "A wrapper around the C FILE struct for rust"
license = "MIT"
edition = "2018"
repository = "https://github.com/jkarns275/cfile"

[dependencies]
libc = "0.2"
